; Ultrasonic Node — ESP32 + HC-SR04
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
upload_port   = /dev/cu.usbserial-3
monitor_port  = /dev/cu.usbserial-3

build_flags =
    -DARDUINO_ARCH_ESP32
    -std=gnu++11
